<?php
/**
 * V1ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ding API
 *
 * The Ding API is a Level 0 REST web service.  We have used the <a href=\"http://swagger.io\">swagger</a> standard to describe this service. As a result, we are able to provide this interactive documentation page. For further information, you may view the <a href=\"/api/description\">additional documentation</a>; read our <a href=\"/api/faq\">FAQ</a> or contact partnersupport@ding.com
 *
 * OpenAPI spec version: V1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.26
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * V1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class V1ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelTransfers
     *
     * CancelTransfers.
     *
     */
    public function testCancelTransfers()
    {
    }

    /**
     * Test case for estimatePrices
     *
     * EstimatePrices.
     *
     */
    public function testEstimatePrices()
    {
    }

    /**
     * Test case for getAccountLookup
     *
     * GetAccountLookup.
     *
     */
    public function testGetAccountLookup()
    {
    }

    /**
     * Test case for getBalance
     *
     * GetBalance.
     *
     */
    public function testGetBalance()
    {
    }

    /**
     * Test case for getCountries
     *
     * GetCountries.
     *
     */
    public function testGetCountries()
    {
    }

    /**
     * Test case for getCurrencies
     *
     * GetCurrencies.
     *
     */
    public function testGetCurrencies()
    {
    }

    /**
     * Test case for getErrorCodeDescriptions
     *
     * GetErrorCodeDescriptions.
     *
     */
    public function testGetErrorCodeDescriptions()
    {
    }

    /**
     * Test case for getProductDescriptions
     *
     * GetProductDescriptions.
     *
     */
    public function testGetProductDescriptions()
    {
    }

    /**
     * Test case for getProducts
     *
     * GetProducts.
     *
     */
    public function testGetProducts()
    {
    }

    /**
     * Test case for getPromotionDescriptions
     *
     * GetPromotionDescriptions.
     *
     */
    public function testGetPromotionDescriptions()
    {
    }

    /**
     * Test case for getPromotions
     *
     * GetPromotions.
     *
     */
    public function testGetPromotions()
    {
    }

    /**
     * Test case for getProviderStatus
     *
     * GetProviderStatus.
     *
     */
    public function testGetProviderStatus()
    {
    }

    /**
     * Test case for getProviders
     *
     * GetProviders.
     *
     */
    public function testGetProviders()
    {
    }

    /**
     * Test case for getRegions
     *
     * GetRegions.
     *
     */
    public function testGetRegions()
    {
    }

    /**
     * Test case for listTransferRecords
     *
     * ListTransferRecords.
     *
     */
    public function testListTransferRecords()
    {
    }

    /**
     * Test case for lookupBills
     *
     * LookupBills.
     *
     */
    public function testLookupBills()
    {
    }

    /**
     * Test case for sendTransfer
     *
     * SendTransfer.
     *
     */
    public function testSendTransfer()
    {
    }
}
